import type { ContentItem } from './schema';

/** BABEL — Langues (anglais). Pouvoir : GLOSSOMANCIE. On réveille les Mots perdus. */
export const BABEL: ContentItem[] = [
  {
    id: 'lv-salut-001',
    royaume: 'babel',
    competence: 'LV.SALUT',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Comment dit-on « Bonjour » en anglais ?',
    choix: ['Goodbye', 'Hello', 'Please', 'Sorry'],
    reponse: 1,
  },
  {
    id: 'lv-salut-002',
    royaume: 'babel',
    competence: 'LV.SALUT',
    difficulte: 2,
    kind: 'qcm',
    enonce: '« Thank you » veut dire…',
    choix: ['Au revoir', 'S’il te plaît', 'Merci', 'Pardon'],
    reponse: 2,
  },
  {
    id: 'lv-nb-001',
    royaume: 'babel',
    competence: 'LV.NOMBRES',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quel nombre est « three » ?',
    choix: ['2', '3', '4', '5'],
    reponse: 1,
  },
  {
    id: 'lv-nb-002',
    royaume: 'babel',
    competence: 'LV.NOMBRES',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Comment écrit-on le nombre 8 en anglais ?',
    choix: ['eight', 'nine', 'seven', 'six'],
    reponse: 0,
  },
  {
    id: 'lv-coul-001',
    royaume: 'babel',
    competence: 'LV.COULEURS',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quelle couleur est « red » ?',
    choix: ['bleu', 'vert', 'rouge', 'jaune'],
    reponse: 2,
  },
  {
    id: 'lv-coul-002',
    royaume: 'babel',
    competence: 'LV.COULEURS',
    difficulte: 3,
    kind: 'qcm',
    enonce: '« Yellow » est la couleur…',
    choix: ['du ciel', 'du soleil', 'de l’herbe', 'de la neige'],
    reponse: 1,
    indice: 'Yellow = jaune, comme le soleil.',
  },
  {
    id: 'lv-vocab-001',
    royaume: 'babel',
    competence: 'LV.VOCAB',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Que signifie « cat » ?',
    choix: ['chien', 'chat', 'cheval', 'oiseau'],
    reponse: 1,
  },
  {
    id: 'lv-vocab-002',
    royaume: 'babel',
    competence: 'LV.VOCAB',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Le mot anglais pour « école » est…',
    choix: ['house', 'school', 'street', 'book'],
    reponse: 1,
  },
];
