import type { ContentItem } from './schema';

/** CHRONOS — Histoire. Pouvoir : CHRONOMANCIE. On répare les Fragments du Temps. */
export const CHRONOS: ContentItem[] = [
  {
    id: 'hist-pre-001',
    royaume: 'chronos',
    competence: 'HIST.PREHISTOIRE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quelle grande découverte marque la maîtrise par les premiers hommes ?',
    choix: ['l’électricité', 'le feu', 'la roue à vapeur', 'l’écriture'],
    reponse: 1,
    indice: 'Il réchauffe, cuit et protège : la Préhistoire en garde la trace.',
  },
  {
    id: 'hist-pre-002',
    royaume: 'chronos',
    competence: 'HIST.PREHISTOIRE',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'La Préhistoire se termine avec l’invention de…',
    choix: ['l’écriture', 'l’imprimerie', 'la monnaie', 'la boussole'],
    reponse: 0,
  },
  {
    id: 'hist-ant-001',
    royaume: 'chronos',
    competence: 'HIST.ANTIQUITE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quel peuple de l’Antiquité a conquis la Gaule ?',
    choix: ['les Égyptiens', 'les Romains', 'les Vikings', 'les Grecs'],
    reponse: 1,
    indice: 'Jules César et ses légions…',
  },
  {
    id: 'hist-ant-002',
    royaume: 'chronos',
    competence: 'HIST.ANTIQUITE',
    difficulte: 3,
    kind: 'saisie',
    enonce: 'Quel chef gaulois a résisté à César à Alésia ? (un prénom)',
    reponse: ['vercingetorix'],
    indice: 'Son nom commence par « Vercin… ».',
  },
  {
    id: 'hist-ma-001',
    royaume: 'chronos',
    competence: 'HIST.MOYENAGE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Au Moyen Âge, qui vivait dans un château fort ?',
    choix: ['le seigneur', 'l’astronaute', 'le pharaon', 'le pirate'],
    reponse: 0,
  },
  {
    id: 'hist-ma-002',
    royaume: 'chronos',
    competence: 'HIST.MOYENAGE',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Quel bâtiment religieux, immense, est typique du Moyen Âge ?',
    choix: ['le gratte-ciel', 'la cathédrale', 'l’usine', 'le temple grec'],
    reponse: 1,
  },
  {
    id: 'hist-mod-001',
    royaume: 'chronos',
    competence: 'HIST.MODERNE',
    difficulte: 3,
    kind: 'saisie',
    enonce: 'En quelle année a commencé la Révolution française ?',
    reponse: ['1789'],
    indice: 'Prise de la Bastille, le 14 juillet…',
  },
  {
    id: 'hist-frise-001',
    royaume: 'chronos',
    competence: 'HIST.FRISE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quelle période vient juste APRÈS l’Antiquité ?',
    choix: ['la Préhistoire', 'le Moyen Âge', 'l’époque contemporaine', 'les Temps modernes'],
    reponse: 1,
    indice: 'Antiquité → … → Temps modernes → Époque contemporaine.',
  },
];
