import type { ContentItem } from './schema';

/** CHROMA — Arts. Pouvoir : CHROMANCIE. On ranime les Couleurs éteintes. */
export const CHROMA: ContentItem[] = [
  {
    id: 'art-coul-001',
    royaume: 'chroma',
    competence: 'ART.COULEURS',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quelles sont les trois couleurs primaires ?',
    choix: ['rouge, jaune, bleu', 'vert, orange, violet', 'noir, blanc, gris', 'rose, marron, or'],
    reponse: 0,
  },
  {
    id: 'art-coul-002',
    royaume: 'chroma',
    competence: 'ART.COULEURS',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Bleu + jaune donne quelle couleur ?',
    choix: ['orange', 'violet', 'vert', 'marron'],
    reponse: 2,
    indice: 'Pense à la couleur de l’herbe.',
  },
  {
    id: 'art-coul-003',
    royaume: 'chroma',
    competence: 'ART.COULEURS',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Rouge + bleu donne…',
    choix: ['vert', 'violet', 'orange', 'gris'],
    reponse: 1,
  },
  {
    id: 'art-oeuv-001',
    royaume: 'chroma',
    competence: 'ART.OEUVRES',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Qui a peint « La Joconde » ?',
    choix: ['Picasso', 'Léonard de Vinci', 'Van Gogh', 'Monet'],
    reponse: 1,
  },
  {
    id: 'art-oeuv-002',
    royaume: 'chroma',
    competence: 'ART.OEUVRES',
    difficulte: 4,
    kind: 'qcm',
    enonce: 'Quel peintre est connu pour ses « Nymphéas » (nénuphars) ?',
    choix: ['Claude Monet', 'Pablo Picasso', 'Salvador Dalí', 'Andy Warhol'],
    reponse: 0,
  },
  {
    id: 'art-mus-001',
    royaume: 'chroma',
    competence: 'ART.MUSIQUE',
    difficulte: 2,
    kind: 'saisie',
    enonce: 'Combien y a-t-il de notes de musique dans la gamme (do, ré, mi…) ?',
    reponse: ['7', 'sept'],
    indice: 'Do, ré, mi, fa, sol, la, si.',
  },
  {
    id: 'art-mus-002',
    royaume: 'chroma',
    competence: 'ART.MUSIQUE',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Quelle note vient juste après « sol » ?',
    choix: ['fa', 'la', 'mi', 'do'],
    reponse: 1,
  },
  {
    id: 'art-mus-003',
    royaume: 'chroma',
    competence: 'ART.MUSIQUE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quel instrument a des touches noires et blanches ?',
    choix: ['la guitare', 'le piano', 'le violon', 'la flûte'],
    reponse: 1,
  },
];
