import type { ContentItem } from './schema';

/** TERRA — Géographie. Pouvoir : GÉOMANCIE. On répare les Fragments de Carte. */
export const TERRA: ContentItem[] = [
  {
    id: 'geo-cont-001',
    royaume: 'terra',
    competence: 'GEO.CONTINENTS',
    difficulte: 2,
    kind: 'saisie',
    enonce: 'Combien y a-t-il de continents sur Terre ?',
    reponse: ['6', 'six'],
    indice: 'Europe, Afrique, Asie, Amérique, Océanie, Antarctique.',
  },
  {
    id: 'geo-cont-002',
    royaume: 'terra',
    competence: 'GEO.CONTINENTS',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Sur quel continent se trouve la France ?',
    choix: ['l’Asie', 'l’Afrique', 'l’Europe', 'l’Océanie'],
    reponse: 2,
  },
  {
    id: 'geo-oce-001',
    royaume: 'terra',
    competence: 'GEO.OCEANS',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Quel est le plus grand océan du monde ?',
    choix: ['l’Atlantique', 'le Pacifique', 'l’océan Indien', 'l’Arctique'],
    reponse: 1,
    indice: 'Il sépare l’Amérique de l’Asie.',
  },
  {
    id: 'geo-fr-001',
    royaume: 'terra',
    competence: 'GEO.FRANCE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quelle est la capitale de la France ?',
    choix: ['Lyon', 'Marseille', 'Paris', 'Bordeaux'],
    reponse: 2,
  },
  {
    id: 'geo-fr-002',
    royaume: 'terra',
    competence: 'GEO.FRANCE',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Quelle chaîne de montagnes sépare la France de l’Espagne ?',
    choix: ['les Alpes', 'les Pyrénées', 'le Jura', 'les Vosges'],
    reponse: 1,
  },
  {
    id: 'geo-fle-001',
    royaume: 'terra',
    competence: 'GEO.FLEUVES',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Quel est le plus long fleuve de France ?',
    choix: ['la Seine', 'le Rhône', 'la Loire', 'la Garonne'],
    reponse: 2,
    indice: 'Il traverse Orléans, Tours et Nantes.',
  },
  {
    id: 'geo-fle-002',
    royaume: 'terra',
    competence: 'GEO.FLEUVES',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quel fleuve traverse Paris ?',
    choix: ['la Loire', 'la Seine', 'le Rhin', 'le Rhône'],
    reponse: 1,
  },
  {
    id: 'geo-carte-001',
    royaume: 'terra',
    competence: 'GEO.CARTE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Sur une carte, où se trouve le Nord par convention ?',
    choix: ['en bas', 'en haut', 'à gauche', 'à droite'],
    reponse: 1,
    indice: 'La rose des vents place le N vers le haut.',
  },
];
