import type { ContentItem } from './schema';

/** VIVARIA — Sciences. Pouvoir : BIOMANCIE. On répare l'Arbre-monde. */
export const VIVARIA: ContentItem[] = [
  {
    id: 'sc-mat-001',
    royaume: 'vivaria',
    competence: 'SC.MATIERE',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quand l’eau gèle, elle passe à l’état…',
    choix: ['liquide', 'solide', 'gazeux', 'invisible'],
    reponse: 1,
    indice: 'La glace est dure : c’est l’état solide.',
  },
  {
    id: 'sc-mat-002',
    royaume: 'vivaria',
    competence: 'SC.MATIERE',
    difficulte: 3,
    kind: 'saisie',
    enonce: 'À quelle température (en °C) l’eau bout-elle au niveau de la mer ?',
    reponse: ['100'],
    indice: 'Trois chiffres, un 1 suivi de deux zéros.',
  },
  {
    id: 'sc-viv-001',
    royaume: 'vivaria',
    competence: 'SC.VIVANT',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Dans une chaîne alimentaire, qui mange la plante ?',
    choix: ['le carnivore', 'le végétal', 'l’herbivore', 'le décomposeur'],
    reponse: 2,
    indice: 'Herbi = herbe. Il mange les végétaux.',
  },
  {
    id: 'sc-viv-002',
    royaume: 'vivaria',
    competence: 'SC.VIVANT',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Quel organe permet aux plantes de capter la lumière ?',
    choix: ['la racine', 'la feuille', 'la tige', 'la graine'],
    reponse: 1,
    indice: 'C’est verte et plate : la photosynthèse s’y fait.',
  },
  {
    id: 'sc-corps-001',
    royaume: 'vivaria',
    competence: 'SC.CORPS',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quel organe pompe le sang dans le corps ?',
    choix: ['le poumon', 'le cœur', 'l’estomac', 'le foie'],
    reponse: 1,
  },
  {
    id: 'sc-astro-001',
    royaume: 'vivaria',
    competence: 'SC.ASTRO',
    difficulte: 2,
    kind: 'qcm',
    enonce: 'Quelle est l’étoile autour de laquelle tourne la Terre ?',
    choix: ['la Lune', 'Mars', 'le Soleil', 'Vénus'],
    reponse: 2,
  },
  {
    id: 'sc-astro-002',
    royaume: 'vivaria',
    competence: 'SC.ASTRO',
    difficulte: 3,
    kind: 'saisie',
    enonce: 'Combien de planètes compte le système solaire ?',
    reponse: ['8', 'huit'],
    indice: 'Depuis 2006, Pluton n’en fait plus partie. Il en reste huit.',
  },
  {
    id: 'sc-ener-001',
    royaume: 'vivaria',
    competence: 'SC.ENERGIE',
    difficulte: 3,
    kind: 'qcm',
    enonce: 'Pour qu’une lampe s’allume, le circuit électrique doit être…',
    choix: ['ouvert', 'fermé', 'coupé', 'mouillé'],
    reponse: 1,
    indice: 'Le courant ne passe que si la boucle est complète : fermée.',
  },
];
